FROM ft-rails:on-build

EXPOSE 3000
CMD [ "rails", "s", "-b", "0.0.0.0", "-p", "3000" ]

# docker build -t ft-rails:on-build .
# git clone https://bitbucket.org/railstutorial/sample_app_4th_ed.git app
# docker build -t ft-rails:on-build ft-rails
# docker build -t ex02 .
# docker run -it --rm -p 3000:3000 ex02
